-- Insert sample shops
INSERT INTO shops (owner_name, manager_name, shop_name, phone, business_doc_url, address_line_1, city, state, country, pin_code, status) VALUES
('Rajesh Kumar', 'Rajesh Kumar', 'Traditional Fashion Hub', '+91-9876543210', 'https://example.com/gst-cert.pdf', '123 Main Street', 'Mumbai', 'Maharashtra', 'India', '400001', 'active'),
('Priya Sharma', 'Priya Sharma', 'Sweet Delights', '+91-9876543211', 'https://example.com/shop-license.pdf', '456 Market Road', 'Delhi', 'Delhi', 'India', '110001', 'active'),
('Amit Patel', 'Amit Patel', 'Handloom Emporium', '+91-9876543212', 'https://example.com/msme-cert.pdf', '789 Artisan Lane', 'Jaipur', 'Rajasthan', 'India', '302001', 'active');

-- Insert sample products
INSERT INTO products (name, description, price, discount_price, category, sub_category, brand, images, rating, review_count, stock, shop_id, status) VALUES
('Men''s Cotton Shirt', 'Premium quality cotton shirt perfect for casual and formal occasions', 1299.00, 999.00, 'Fashion', 'Men''s Shirts', 'Traditional Hub', ARRAY['https://example.com/shirt1.jpg', 'https://example.com/shirt2.jpg'], 4.5, 234, 50, (SELECT id FROM shops WHERE shop_name = 'Traditional Fashion Hub'), 'active'),
('Women''s Silk Saree', 'Beautiful silk saree with traditional Indian designs', 3999.00, 2999.00, 'Fashion', 'Women''s Sarees', 'Royal Silks', ARRAY['https://example.com/saree1.jpg', 'https://example.com/saree2.jpg'], 4.8, 156, 25, (SELECT id FROM shops WHERE shop_name = 'Traditional Fashion Hub'), 'active'),
('Motichur Ladoo', 'Traditional Indian sweet made from gram flour and sugar syrup', 599.00, NULL, 'Foods', 'Sweets', 'Sweet Delights', ARRAY['https://example.com/ladoo1.jpg'], 4.6, 89, 100, (SELECT id FROM shops WHERE shop_name = 'Sweet Delights'), 'active'),
('Aloo Bhujia', 'Crispy and spicy potato snack perfect for tea time', 199.00, 149.00, 'Foods', 'Namkeen', 'Rajasthani Snacks', ARRAY['https://example.com/bhujia1.jpg'], 4.3, 267, 200, (SELECT id FROM shops WHERE shop_name = 'Sweet Delights'), 'active'),
('Banarasi Silk Fabric', 'Authentic Banarasi silk fabric for traditional wear', 2499.00, NULL, 'Handlooms', 'Fabrics', 'Banarasi Weavers', ARRAY['https://example.com/fabric1.jpg', 'https://example.com/fabric2.jpg'], 4.7, 78, 30, (SELECT id FROM shops WHERE shop_name = 'Handloom Emporium'), 'active'),
('Kashmiri Shawl', 'Hand-woven Kashmiri shawl with intricate embroidery', 5999.00, 4999.00, 'Handlooms', 'Shawls', 'Kashmir Crafts', ARRAY['https://example.com/shawl1.jpg', 'https://example.com/shawl2.jpg'], 4.9, 45, 15, (SELECT id FROM shops WHERE shop_name = 'Handloom Emporium'), 'active'),
('Kaju Katli', 'Delicious cashew nut barfi with silver vark', 899.00, 799.00, 'Foods', 'Sweets', 'Royal Sweets', ARRAY['https://example.com/katli1.jpg'], 4.8, 123, 75, (SELECT id FROM shops WHERE shop_name = 'Sweet Delights'), 'active'),
('Denim Jeans', 'Comfortable denim jeans for everyday wear', 1599.00, 1299.00, 'Fashion', 'Men''s Jeans', 'Denim Co', ARRAY['https://example.com/jeans1.jpg', 'https://example.com/jeans2.jpg'], 4.4, 189, 40, (SELECT id FROM shops WHERE shop_name = 'Traditional Fashion Hub'), 'active'),
('Cotton Kurti', 'Comfortable cotton kurti with modern designs', 899.00, 699.00, 'Fashion', 'Women''s Kurtis', 'Fashion Hub', ARRAY['https://example.com/kurti1.jpg', 'https://example.com/kurti2.jpg'], 4.5, 156, 60, (SELECT id FROM shops WHERE shop_name = 'Traditional Fashion Hub'), 'active'),
('Rasgulla', 'Soft and spongy cottage cheese balls in sugar syrup', 499.00, NULL, 'Foods', 'Sweets', 'Bengal Sweets', ARRAY['https://example.com/rasgulla1.jpg'], 4.6, 234, 80, (SELECT id FROM shops WHERE shop_name = 'Sweet Delights'), 'active'),
('Glass Vase', 'Decorative glass vase with traditional Indian patterns', 1299.00, 999.00, 'Glassware', 'Decorative Items', 'Glass Art', ARRAY['https://example.com/vase1.jpg', 'https://example.com/vase2.jpg'], 4.4, 67, 25, (SELECT id FROM shops WHERE shop_name = 'Traditional Fashion Hub'), 'active'),
('Clay Pot', 'Traditional clay pot for cooking and decoration', 399.00, 299.00, 'Pottery', 'Traditional Items', 'Earth Crafts', ARRAY['https://example.com/pot1.jpg', 'https://example.com/pot2.jpg'], 4.5, 89, 50, (SELECT id FROM shops WHERE shop_name = 'Handloom Emporium'), 'active'),
('Rose Attar', 'Traditional Indian rose perfume oil', 799.00, 699.00, 'Perfumes', 'Indian Attars', 'Herbal Scents', ARRAY['https://example.com/attar1.jpg'], 4.7, 145, 60, (SELECT id FROM shops WHERE shop_name = 'Sweet Delights'), 'active'),
('Incense Sticks', 'Natural incense sticks for meditation and prayer', 299.00, 249.00, 'Perfumes', 'Incense', 'Divine Fragrance', ARRAY['https://example.com/incense1.jpg'], 4.3, 278, 150, (SELECT id FROM shops WHERE shop_name = 'Sweet Delights'), 'active'),
('Tussar Silk Saree', 'Elegant tussar silk saree with natural golden sheen', 4999.00, 3999.00, 'Fashion', 'Women''s Sarees', 'Silk Valley', ARRAY['https://example.com/tussar1.jpg', 'https://example.com/tussar2.jpg'], 4.9, 34, 20, (SELECT id FROM shops WHERE shop_name = 'Handloom Emporium'), 'active');
